name: Android CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - '.github/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Gradle
        run: |
          echo "commit=$(echo ${{ github.sha }} | cut -c-7)" >> $GITHUB_ENV
          touch signing.properties
          echo storeFile=../keystore.jks >> signing.properties
          echo storePassword=${{ secrets.KEYSTORE_PASSWORD }} >> signing.properties
          echo keyAlias=${{ secrets.KEYSTORE_ALIAS }} >> signing.properties
          echo keyPassword=${{ secrets.KEYSTORE_ALIAS_PASSWORD }} >> signing.properties
          echo ${{ secrets.KEYSTORE }} | base64 --decode > keystore.jks
          ./gradlew assembleRelease
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hail@${{ env.commit }}
          path: app/build/outputs/apk/release/*.apk
